MerlinofMines/EasyCommands

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ScriptTests/ConditionalBlockExecutionTests.cs, EasyCommands.Tests/ScriptTests/ScriptTest.cs, EasyCommands.Tests/ScriptTests/SimpleBlockCommandTests.cs, EasyCommands.Tests/ScriptTests/SimpleCommandExecutionTests.cs, EasyCommands.Tests/Util/Extensions.cs, EasyCommands/BlockHandlers/BlockHandlers.cs, EasyCommands/Commands/EntityProviders.cs, EasyCommands/Program.cs
Revamped ScriptTests by adding ScriptTest utility class
This greatly reduces the required boilerplate in writing script tests
by delegating most of that to the construction of a ScriptTest instance.
ScriptTest authors only need to provide the actual script,
the mocked objects, and the verifications/assertions for those mocks.
As part of this, I replaced block and group entity providers with
mocking of the GridTerminalSystem. However, I haven't yet configured
it to work properly for display blocks. I wanted to get this bit out
and reviewed before then proceeding to address the display block gap.
As a result, you'll see changes to EasyCommands for the removal of the
block provider delegates, as those are no longer required.
Other notable changes:
* Changed STATE in Program to be public so …
=> Revamped ScriptTests by adding ScriptTest utility class

EasyCommands.Tests/ParameterParsingTests/SimpleCommandProcessorTests.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/CommandParsers/ParameterProcessors.cs, EasyCommands/Commands/Commands.cs, EasyCommands/Common/Types.cs
This commit significantly reduces expensive boilerplate code for ParameterProcessors by moving almost all processors to use a RuleProcessor and delegates.  This has
dramatically reduced the file and character size of ParameterProcessors.
I also added some missing tests for Iteration and Control command parameter processing.
I also removed some now unneeded constructors for some command types.
I also removed "Resume" as a specific control type and changed "Start" to act like Resume, as it had no purpose previously (was the same as Restart which didn't
quite make sense anyway).
Lastly, I changed the ParameterProcessor ranking to be set specifically be the list ordering instead of being inferred by type, as this was a problem for multiple
rule based processors that need to process the same …
=> Refactored ParameterProcessors to use Rule Based Processing

EasyCommands.Tests/ParameterParsingTests/AggregateBlockPropertyProcessorTests.cs, EasyCommands.Tests/ParameterParsingTests/BlockCommandProcessorTests.cs, EasyCommands.Tests/ParameterParsingTests/BooleanLogicParameterProcessorTests.cs, EasyCommands.Tests/ParameterParsingTests/ConditionalParameterProcessorTests.cs, EasyCommands.Tests/ParameterParsingTests/OperatorParameterProcessorTests.cs, EasyCommands.Tests/ParameterParsingTests/ParenthesisParameterProcessorTests.cs, EasyCommands.Tests/ParameterParsingTests/SelectorLogicParameterProcessorTests.cs, EasyCommands.Tests/ParameterParsingTests/SimpleCommandProcessorTests.cs, EasyCommands.Tests/ParameterParsingTests/SimpleVariableParameterProcessorTests.cs, EasyCommands.Tests/TokenParsingTests/StringParsingTests.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/CommandParsers/ParameterProcessors.cs, EasyCommands/Commands/CommandParameters.cs
This fix, built on top of pull #35 , fixes an outstanding bug where you can't assign variables or call functions using an explicit string.
Specifically, this commit fixes #27
This commit also moves all the processor tests to the correct namespace and moves the variable assignment tests into SimpleVariableParamterProcessorTests
=> Fixed Explicit Strings not working for Assignment and Function Calls

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ScriptTests/CameraBlockTests.cs, EasyCommands.Tests/ScriptTests/MockEntityUtility.cs, EasyCommands.Tests/ScriptTests/SensorBlockTests.cs, EasyCommands/BlockHandlers/BlockHandlers.cs, EasyCommands/BlockHandlers/CameraBlockHandlers.cs, EasyCommands/BlockHandlers/SensorBlockHandlers.cs, EasyCommands/Common/Operations.cs, EasyCommands/Common/Primitives.cs
This commit adds basic target support for Camera and Sensor Blocks
It also fixed a couple bugs with getting and setting custom properties which were discovered during testing.
Also adds block handler tests for Camera and Sensor Blocks along with a MockEntityUtility for adding commonly used mocks in the future.
This implements #30
=> Added target support to Camera and Sensor Blocks

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ScriptTests/RotorBlockTests.cs, EasyCommands/BlockHandlers/RotorBlockHandlers.cs, EasyCommands/CommandParsers/ParameterProcessors.cs, EasyCommands/Commands/Commands.cs, EasyCommands/Common/Primitives.cs
This commit mostly fixes the issue with rotor angle not obeying directions.  It turns out there are some cases where the game itself won't properly wrap around.
I added tests for the cases where obeying direction should now work.
I found multiple bugs introduced by previous changes as part of this which also had to be fixed, including:
* Subtraction Operation was not working correctly (was adding)
* SetPropertyDirection was ignoring direction for all blocks, not just rotors
* Increment/Decrement commands were broken as the relative command parameter was passed to BlockCommand twice.
This commit fixes #14
=> Fixed Bug with Rotor angle not honoring direction

EasyCommands.Tests/ParameterParsingTests/AggregateBlockPropertyProcessorTests.cs, EasyCommands.Tests/ParameterParsingTests/BooleanLogicParameterProcessorTests.cs, EasyCommands.Tests/ParameterParsingTests/SelectorLogicParameterProcessorTests.cs, EasyCommands/BlockHandlers/BlockHandlers.cs, EasyCommands/BlockHandlers/TextSurfaceHandlers.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/CommandParsers/ParameterProcessors.cs, EasyCommands/Commands/EntityProviders.cs
This change allows you to perform an action on all blocks of a given type without defining a group.
The new selectors can be used in block commands to perform actions, or in aggregate block conditions to check for block state.
You can also use this to get aggregate block properties.
I messed up the last pull request #43 , resubmitting
=> Added "all" and implicit selector support

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ScriptTests/MockEntityUtility.cs, EasyCommands.Tests/ScriptTests/ScriptTest.cs, EasyCommands.Tests/ScriptTests/SubclassBlockTests.cs, EasyCommands.Tests/ScriptTests/TextSurfaceBlockTests.cs
This commit adds support for mocking text surfaces on text surface providers.  It also adds tests confirming we can now test textsurfaces.
Additionally, this commit replaces our mock block grid and mock block groups with a proper implementation to overcome the issues with subclass casting which the
moq framework can't really deal with.
This commit resolves #46
=> Added TextSurface and Subclass Mocking Support

EasyCommands.Tests/ParameterParsingTests/SelectorLogicParameterProcessorTests.cs, EasyCommands.Tests/ScriptTests/SimpleBlockCommandTests.cs, EasyCommands/CommandParsers/ParameterProcessors.cs, EasyCommands/Commands/Commands.cs, EasyCommands/Commands/EntityProviders.cs
This commit makes blockType in SelectorEntityProvider an optional field, and adds just in time blockType & group resolution if blockType is not present.
This also involved making some changes to BlockCommand, which was pre-parsing blockType during compilation.
Additionally, the processor for variableSelector has been relaxed to allow optional blockType.  The result is implicit block type resolution for variable selectors.
Lastly, this commit adds parsing and script tests showing the new implicit variable selectors can now be used in block commands and conditions.
This commit resolves #56
=> Added Implicit Variable Selector Block Type Support

EasyCommands.Tests/ScriptTests/MultiThreadingTests.cs, EasyCommands/Commands/Commands.cs
This commit changes the current behavior so that all thread variables are passed to a queued/async command as they were at the time that the command was queued.
This gives the queued/async thread access to the variable state and allows you to pass in memory variables as parameters to queued/async threads.
With this change, this commit solves a couple different problems.
Problem 1: You can't use an in-memory variable as a parameter to a queued or async function because the queued thread isn't aware of the variables you had when you
called it.  So when it tries to resolve the variable..it's not there!  You can solve this by making the variable global, but this leads to problem #2.
Problem 2: Global In-Memory Variables do not honor the state they were in when a queued or async method was …
=> Added support for passing variables to queued commands

EasyCommands.Tests/ParameterParsingTests/SimpleVariableParameterProcessorTests.cs, EasyCommands/CommandParsers/ParameterProcessors.cs
This commit uses the new branching support to add new parsing support for parsing double quoted strings containing block type tokens.
Before this commit, a command like assign "v" to "my piston" would fail as "my piston" is interpreted as a selector and then the command will not parse.
This commit introduced a new branch to interpret all double quoted strings as an explicit string.  The result is that the above command now parses.
This has some ramifications to Implicite Aggregate Properties, as we must distinguish between an explicit string and an implicite aggregate property in this case.
The following rules, implemented by this CR, disambiguate:
1.  If the aggregator is specified (count, sum, avg) then property is optional as there is no ambiguity.
2.  If an implicit aggregator is …
=> Added Support for Double Quote Explicit Strings

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ScriptTests/SimpleLoggingTests.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/CommandParsers/ParameterProcessors.cs, EasyCommands/Commands/CommandParameters.cs, EasyCommands/Commands/Commands.cs, EasyCommands/Commands/EntityProviders.cs, EasyCommands/Program.cs
This commit implements much better processor debugging support with 2 commits:
1 - Add the parse tree to the debug output.  When LogLevel is set to Debug, the output will contain detailed information about how the command was parsed.
2 - Add line numbers to the exception output when a command cannot be parsed.  
This commit implements #13
=> Parameter processor debugging enhancement

EasyCommands.Tests/ScriptTests/MultiThreadingTests.cs, EasyCommands/Commands/Commands.cs
This simple commit fixes a bug where parameters would only get set once in a while loop, leading to failures if the command inside the while loop is a queue command
call.
=> Fixed Parameters Not Set Correctly in While Loops

EasyCommands.Tests/ScriptTests/TextSurfaceBlockTests.cs, EasyCommands/Common/Primitives.cs
This commit simply treats all instances of "\n" as a carriage return by replacing those strings before returning the primitive value.
It also adds a simple test proving the behavior is working as expected
This commit implements #69
=> Added simple multi-line text support

EasyCommands.Tests/ParameterParsingTests/AggregateBlockPropertyProcessorTests.cs, EasyCommands.Tests/ParameterParsingTests/BlockCommandProcessorTests.cs, EasyCommands.Tests/ParameterParsingTests/BooleanLogicParameterProcessorTests.cs, EasyCommands.Tests/ParameterParsingTests/ConditionalParameterProcessorTests.cs, EasyCommands.Tests/ParameterParsingTests/OperatorParameterProcessorTests.cs, EasyCommands.Tests/ParameterParsingTests/ParenthesisParameterProcessorTests.cs, EasyCommands.Tests/ParameterParsingTests/SelectorLogicParameterProcessorTests.cs, EasyCommands.Tests/ParameterParsingTests/SimpleCommandProcessorTests.cs, EasyCommands.Tests/ParameterParsingTests/SimpleVariableParameterProcessorTests.cs, EasyCommands.Tests/ScriptTests/ScriptTest.cs, EasyCommands.Tests/ScriptTests/SimpleCommandExecutionTests.cs, EasyCommands.Tests/ScriptTests/SimpleLoggingTests.cs, EasyCommands.Tests/TokenParsingTests/ParenthesisParsingTests.cs, EasyCommands.Tests/TokenParsingTests/StringParsingTests.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/CommandParsers/ParameterProcessors.cs, EasyCommands/Commands/EntityProviders.cs, EasyCommands/Common/Primitives.cs, EasyCommands/Program.cs
This pull request drastically reduces the character size of ParameterParsers, and removes almost all static references in Program.
The one remaining static reference, arguably the most difficult to remove, is PROGRAM.  This attribute is used in various places across the code, and actually makes the management of many classes easier.  As such, I've decided it's not worth removing this reference, both because it adds more characters to leave it than it does to try and remove it, and because it makes many of the interfaces more cluttered.
As such, this commit should resolve as much of #74 as is reasonable
This set of commits brings the total character count for the program down to 81783
=> Remove statics

EasyCommands.Tests/ParameterParsingTests/SimpleVariableParameterProcessorTests.cs, EasyCommands/CommandParsers/ParameterProcessors.cs
I've seen a few times (and done this myself) where a user tries to say:
"assign {a} to {b}" since normally you use {} or []to interact with a variable.
Currently you have to do either:
assign "a" to {b}
assign 'a' to {b}
Now you can also do
assign {a} to {b}
assign [a] to {b}
=> Added support for assigning variables using the variable syntax {}

EasyCommands.Tests/ScriptTests/LightBlockTests.cs, EasyCommands/Common/Primitives.cs
This commit adds some simple support for parsing a color from a vector, using X as red, Y as green, and Z as blue
Implements #81
=> Added Color Parsing From Vector Support

EasyCommands.Tests/ParameterParsingTests/ListParameterProcessorTests.cs, EasyCommands.Tests/ParameterParsingTests/OperatorParameterProcessorTests.cs, EasyCommands.Tests/ScriptTests/SimpleListTests.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/CommandParsers/ParameterProcessors.cs, EasyCommands/Commands/CommandParameters.cs, EasyCommands/Common/Collections.cs, EasyCommands/Common/Operations.cs, EasyCommands/Common/Primitives.cs, EasyCommands/Common/Types.cs, EasyCommands/Common/Variables.cs, EasyCommands/EasyCommands.csproj
This commit adds on to #93 by adding dictionary support.  Collections has been pulled into it's own primitive type which stores a list of optionally keyed values.
You can get or set values in a list by specifying a string variable instead of a numeric variable as the index.
You can also get a keyed sublist by asking for multiple string keys. 
I also added support for 2 new operations on lists, namely "keys" and "values", for retrieving just the keys or just the values from a keyed list (similar to dictionary).  Non-keyed values will not be returned by "keys", but all values are returned by "values".
Merging keyed lists de-dupes string based index values, keeping the only the keyed values from the 2nd list but otherwise maintaining the order.
It also adds new support for removing items …
=> Dictionary support enhancement

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ParameterParsingTests/SelectorLogicParameterProcessorTests.cs, EasyCommands.Tests/ParameterParsingTests/SimpleVariableParameterProcessorTests.cs, EasyCommands.Tests/ScriptTests/LightBlockTests.cs, EasyCommands.Tests/ScriptTests/ScriptTest.cs, EasyCommands.Tests/ScriptTests/SimpleSelectorTests.cs, EasyCommands/BlockHandlers/BlockHandlers.cs, EasyCommands/BlockHandlers/CargoBlockHandlers.cs, EasyCommands/BlockHandlers/TextSurfaceHandlers.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/CommandParsers/ParameterProcessors.cs, EasyCommands/Commands/CommandParameters.cs, EasyCommands/Commands/EntityProviders.cs
This commit adds list index support to selectors so that you can fetch sub items by index from selectors.
numeric indexes act just like existing index selector where it looks for block list @ (index)
string indexes work by using the entity "name" as a filter.  This allows you to request that only blocks with a specific name in a specific group should do a thing.   You can also pass in a list of numeric+string indexes which will use blocks matching any of the numeric or string indexes.
Indexes can be specified with either the old format
``` "selector" @ index ``` , or with the list index format 
``` "selector" [index]```
It also refactors a little bit of how string command parameters are parsed which simplified some redundant parsing rules.
Lastly, it pulls up all selector parsing logic to …
=> Selector list index enhancement

EasyCommands.Tests/ParameterParsingTests/BlockCommandProcessorTests.cs, EasyCommands.Tests/ParameterParsingTests/SimpleVariableParameterProcessorTests.cs, EasyCommands.Tests/ScriptTests/SimpleListTests.cs, EasyCommands.Tests/ScriptTests/SimpleVariableTests.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/CommandParsers/ParameterProcessors.cs, EasyCommands/Commands/CommandParameters.cs
Having to remember to use "assign" instead of "set" when setting variables is annoying.  After moving Selector processing to the top of the parsing tree, it's now possible to combine "Action" and "Assignment".  Now you can set variables, list indexes, etc using "set" instead of "assign".  Conversely, you can initiate block commands using "assign", such as 'assign the "test pistons" height to 10'
=> Combined Action and Assignment Command Parameters

docs/EasyCommands/operations.md
This would have fixed the issue i originally opened #123  for.
=> Fix spelling mistake in XOR documentation

EasyCommands.Tests/ParameterParsingTests/OperatorParameterProcessorTests.cs, EasyCommands.Tests/ScriptTests/ExampleScriptTests/RotorControlTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/SimpleVariableTests.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/CommandParsers/ParameterProcessors.cs, EasyCommands/CommandParsers/ProcessingEngine.cs, EasyCommands/Commands/CommandParameters.cs, docs/EasyCommands/operations.md, docs/EasyCommands/parsing.md
This commit adds support for "-" to mean either subtraction or negation, depending on it's surrounding context.  This effectively enables support for negating
variables without requiring -1 * variable.  Now you can simply do -variable.  Negation takes precedence, so -a-a = (-a) - a, vs -(a-a).
This commit also changes parentheses processing to throw out branches that do not resolve to a single value.  The new expectation is that anything in parentheses
should resolve to a single value, be it a selector, variable or command.
=> Minus Operation Support

EasyCommands.Tests/ScriptTests/BlockHandlerTests/ProgramBlockTests.cs, EasyCommands/BlockHandlers/ProgrammableBlockHandlers.cs, EasyCommands/CommandParsers/ParameterParsers.cs, docs/EasyCommands/blockHandlers/program.md, docs/EasyCommands/cheatsheet.md
This commit adds "programmable" as a block word for Programmable Blocks, adds "argument" as a text property keyword, and defaults "Run" to use the default terminal
argument instead of ""
=> Programmable Block Improvements

EasyCommands.Tests/ScriptTests/BlockHandlerTests/GyroscopeBlockTests.cs, EasyCommands/BlockHandlers/BlockHandlers.cs, EasyCommands/BlockHandlers/GyroscopeBlockHandlers.cs, docs/EasyCommands/blockHandlers/gyroscope.md
This commit fixes Gyro Overrides support to propertly use RPM, vs a weird % that didn't really work right.
It also extends "overrides" support to include vector, numeric and boolean.
Also, the Power property now controls Gyro power.
This PR resolves #108
=> Gyro Block Improvements

EasyCommands.Tests/ScriptTests/BlockHandlerTests/GravityBlockTests.cs, EasyCommands/BlockHandlers/GravityGeneratorBlockHandlers.cs, docs/EasyCommands/blockHandlers/gravityGenerator.md, docs/EasyCommands/blockHandlers/gravitySphere.md
This commit adds the Level property to Gravity and Spherical Gravity Generator Blocks.  Also added a missing default property for gravity spheres.
This PR resolves #118
=> Gravity Generator Block Improvements

EasyCommands.Tests/ScriptTests/BlockHandlerTests/ThrustBlockTests.cs, EasyCommands/BlockHandlers/ThrusterBlockHandlers.cs, docs/EasyCommands/blockHandlers/thruster.md
This commit adds output as a property to ThrusterBlock, and fixes some documentation around a few properties.
This commit resolves #113
=> ThrusterBlockImprovements

EasyCommands.Tests/ParameterParsingTests/OperatorParameterProcessorTests.cs, EasyCommands.Tests/ScriptTests/BlockHandlerTests/TextSurfaceBlockTests.cs, EasyCommands/BlockHandlers/TextSurfaceHandlers.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/Common/Operations.cs, EasyCommands/Common/Types.cs, docs/EasyCommands/blockHandlers/connector.md, docs/EasyCommands/blockHandlers/display.md, docs/EasyCommands/blockHandlers/landingGear.md, docs/EasyCommands/blockHandlers/laserAntenna.md, docs/EasyCommands/blockHandlers/merge.md, docs/EasyCommands/cheatsheet.md, docs/EasyCommands/operations.md
This commit also fixes a couple issues with Text Surfaces.  First, the Name property was missing.  Second, "GetText()" wasn't working.  Replaced with ReadText().
This commit also re-purposes "split, join, joined, separate, separated" to the new operations and removes them from the connected property.
This commit resolves #130
=> Added Split and Join Operations

EasyCommands.Tests/ScriptTests/FunctionalTests/BlockHandlers/TextSurfaceBlockTests.cs, EasyCommands/BlockHandlers/TextSurfaceHandlers.cs
Looks like this one was missed as part of the Enabled fix previously.  Docs already mention that Enabled is the default property
=> Added missing default boolean property to Display block

EasyCommands/CommandParsers/ParameterParsers.cs
While investigating #159 i found some unneeded code.
Instead of first splitting, joining, copying (or rather: constructing a new string from the old ones char array that is cast to a list) and then splitting again, the the first split operation is returned directly. Also the loops to add spaces around the tokens got moved into its own method.
For a few characters more `ParseSurrounded`, `ParseSeperateTokens` and the lambda in `ParseTokens` could return `IEnumerator<...>` and the `toArray` calls could be removed.
This would make these functions truely lazy and maybe give a small performance boost on the tokenizing step.
=> Refactor `ParseSeperatorTokens`

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/TokenizeTests/BlueprintParsingTests.cs, EasyCommands.Tests/TokenizeTests/BracketTests.cs, EasyCommands.Tests/TokenizeTests/FloatingPointTests.cs, EasyCommands.Tests/TokenizeTests/ItemParsingTests.cs, EasyCommands.Tests/TokenizeTests/ParenthesisTests.cs, EasyCommands.Tests/TokenizeTests/StringTests.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/CommandParsers/ParsingEngine.cs, EasyCommands/Commands/Selectors.cs
This PR implements the changes discussed in #170 and renames the tests accordingly.
Switching from `String[]` to  `IEnumerable<String>` removes quite a number of allocations and does speed up the unit testing by about a third on my system.
_I dont like the implementation very much but C# especially v6 is limiting._
=> Rework tokenizing

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ScriptTests/FunctionalTests/Commands/ListenCommandTests.cs, EasyCommands.Tests/ScriptTests/ScriptTest.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/CommandParsers/ProcessingEngine.cs, EasyCommands/Commands/CommandParameters.cs, EasyCommands/Commands/Commands.cs, EasyCommands/Program.cs, docs/EasyCommands/cheatsheet.md, docs/EasyCommands/commands.md
This commit adds the ability to forget a previously listened to channel and adds additional words for listening and forgetting channels.
This commit also adds some previously missing tests for the ListenCommand.
Resolves #168
=> Added Forget Command Support

EasyCommands.Tests/ScriptTests/FunctionalTests/Primitives/SimpleListTests.cs, EasyCommands/Common/Collections.cs, EasyCommands/Common/Variables.cs
This commit fixes an issue where appending to lists previously would not keep static values but rather references.  This caused variable additions to be reference and have changing values.
Binding keyed indexes still works as expected but this fixes an issue where adding values was not working as expected.
This commit resolves #187
=> Fixed issue where combining lists used references instead of values

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ParameterParsingTests/SimpleCommandProcessorTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/Commands/FunctionCommandTests.cs, EasyCommands/CommandParsers/ParameterProcessors.cs, EasyCommands/CommandParsers/ProcessingEngine.cs, EasyCommands/Commands/CommandParameters.cs, EasyCommands/Commands/Commands.cs, EasyCommands/Common/Utilities.cs, EasyCommands/EasyCommands.csproj, docs/EasyCommands/functions.md
This commit adds the ability to invoke functions dynamically using variables.  This is a powerful feature, but comes at the cost of compile time safety.
This commit moves the resolution of the function name to invoke to a runtime call.  It also leaves the resolution of parameter key names to runtime.  The existing
error messages have been improved, but will now show up as runtime exceptions.
Lastly, this commit introduces a "Utilities" section to contain some useful utilities for saving characters on Type and Function declarations.
This commit resolves #172
=> Added support for Dynamic Function Execution

docs/EasyCommands/primitives.md
This commit adds docs inside of the Primitive docs for using the newline character and for creating vectors via variables.
This commit resolves #154
=> Added missing docs for newline char (\n) and Variable Vectors

EasyCommands.Tests/ParameterParsingTests/OperatorParameterProcessorTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/BlockHandlers/GyroscopeBlockTests.cs, EasyCommands/BlockHandlers/GyroscopeBlockHandlers.cs, EasyCommands/Common/Collections.cs, EasyCommands/Common/Operations.cs, EasyCommands/Common/Utilities.cs, docs/EasyCommands/blockHandlers/cockpit.md, docs/EasyCommands/blockHandlers/gyroscope.md, docs/EasyCommands/operations.md
* add `round` operator for vectors
* move some function from Collections.cs to Utilities.cs
* use gyro properties directly again and introduce constant for conversion from RPM to rad/s and viceversa
each vector component is seperatly multiplied by the conversion factors so the test does not fail because of float to double promotion.
=> Small Changes

EasyCommands.Tests/ScriptTests/FunctionalTests/BlockHandlers/CockpitBlockTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/BlockHandlers/CryoChamberBlockTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/BlockHandlers/ParachuteBlockTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/BlockHandlers/RemoteControlBlockTests.cs, EasyCommands/BlockHandlers/ParachuteBlockHandlers.cs, EasyCommands/BlockHandlers/ShipControllerHandlers.cs, docs/EasyCommands/blockHandlers/cockpit.md, docs/EasyCommands/blockHandlers/parachute.md, docs/EasyCommands/blockHandlers/remote.md
This commit changes parachutes, cockpits and remote controls to return a Vector for velocity instead of just it's magnitude.
This PR resolves #194
=> Updated Velocity properties to use vectors

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ScriptTests/FunctionalTests/Operations/RoundOperatorTests.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/CommandParsers/ProcessingEngine.cs, EasyCommands/Commands/CommandParameters.cs, EasyCommands/Common/Operations.cs, EasyCommands/Common/Types.cs, docs/EasyCommands/cheatsheet.md, docs/EasyCommands/operations.md
This commit expands the Round operation to support an optional number of digits to round the given number to.  It also adds support for specifying the round
operation before or after the given number or vector to be rounded.
This PR resolves #179
=> Round Operation Improvements

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ParameterParsingTests/OperatorParameterProcessorTests.cs, EasyCommands.Tests/ParameterParsingTests/SimpleVariableParameterProcessorTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/BlockHandlers/LaserAntennaBlockTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/BlockHandlers/LightBlockTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/Operations/SimpleCastTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/Primitives/SimpleStringTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/Primitives/SimpleVectorTests.cs, EasyCommands/BlockHandlers/GyroscopeBlockHandlers.cs, EasyCommands/CommandParsers/ParameterProcessors.cs, EasyCommands/CommandParsers/ProcessingEngine.cs, EasyCommands/Commands/CommandParameters.cs, EasyCommands/Common/Primitives.cs, EasyCommands/Common/Utilities.cs, EasyCommands/Common/Variables.cs, EasyCommands/Program.cs, docs/EasyCommands/operations.md, docs/EasyCommands/primitives.md
This commit changes string parsing so that anything wrapped in double quotes is not automatically converted to primitives.  Direct values can still be used, as can
conversions from string to the requested formats.
Also removed PrimitiveProcessor which is no longer needed.
=> Changed String Primitive Parsing

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ScriptTests/FunctionalTests/Operations/Comparisons/SimpleInvalidComparisonsTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/Operations/RoundOperatorTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/Operations/SimpleCastTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/Operations/SimpleTypeOperatorTests.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/CommandParsers/ProcessingEngine.cs, EasyCommands/Commands/CommandParameters.cs, EasyCommands/Common/Operations.cs, EasyCommands/Common/Primitives.cs, EasyCommands/Common/Types.cs, docs/EasyCommands/operations.md, docs/EasyCommands/primitives.md
This PR updates the cast operation to act as either a UniOperand or a BiOperand.  As a UniOperand it will attempt to parse a string as the appropriate primitive
without needing to specify the expected type.  This is useful for parsing ambiguous input without causing script halting exceptions.
This commit also implements the Type operation, which enables you to get the type of a variable.  This is also useful for inspecting resolved input to verify it is
the correct type before attempting to use it as the type you are expecting.
This commit also fixes a previous bug where invalid cast and round operations were not logged correctly.
This commit also updates some incorrect documentation around vectors and adds documentation around parsing GPS coordinates.
=> Added UniOperand Cast and Type Operand Support

EasyCommands.Tests/ScriptTests/FunctionalTests/Commands/ControlCommandTests.cs, EasyCommands/CommandParsers/ParameterParsers.cs
This commit changes the behavior of return so that if you call it outside of a function, it terminates the current thread instead of throwing an exception.
=> Changed Return to End Thread When Outside Function Call

EasyCommands.Tests/ScriptTests/FunctionalTests/Commands/ComplexBlockCommandTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/Variables/MultiWordPropertyAggregationTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/Variables/SimpleAggregationTests.cs, EasyCommands/CommandParsers/CommandParameters.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/CommandParsers/ProcessingEngine.cs, EasyCommands/Common/Properties.cs, docs/EasyCommands/blockHandlers.md
This PR adds a useful feature for specifying block properties by enabling the user to specify the property word(s) in front of the selector, such as:
```print "Range: " + the range of my turrets```
It also removes the unnecessary "BooleanCommandParameter" type, which was only used to indicate inversion of properties.  This has been moved directly onto the property parameter.
=> Flexible property support

EasyCommands.Tests/ScriptTests/FunctionalTests/BlockHandlers/ConnectorBlockTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/BlockHandlers/JumpDriveBlockTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/BlockHandlers/LandingGearBlockTests.cs, EasyCommands/BlockHandlers/ConnectorBlockHandlers.cs, EasyCommands/BlockHandlers/JumpDriveBlockHandlers.cs, EasyCommands/BlockHandlers/LandingGearHandlers.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/CommandParsers/ProcessingEngine.cs, EasyCommands/Common/Types.cs, docs/EasyCommands/blockHandlers/connector.md, docs/EasyCommands/blockHandlers/jumpDrive.md, docs/EasyCommands/blockHandlers/landingGear.md, docs/EasyCommands/cheatsheet.md
This commit adds a new property for "Able", as well as a small processing rule to handle "ready to connect" and similar phrases.
It also adds new "ready to connect/lock" support to landing gear and connectors.
=> Added Able (ready) Property

EasyCommands.Tests/ScriptTests/FunctionalTests/Variables/SimpleAggregationTests.cs, EasyCommands/BlockHandlers/BlockHandlers.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/CommandParsers/ProcessingEngine.cs, EasyCommands/Common/Aggregators.cs, EasyCommands/Common/Types.cs, docs/EasyCommands/blockHandlers/display.md, docs/EasyCommands/blockHandlers/inventory.md, docs/EasyCommands/blockHandlers/terminal.md, docs/EasyCommands/cheatsheet.md, docs/EasyCommands/variables.md
This commit changes the default aggregation mode to use a new special default aggregation instead of a sum.  This aggregation will return an empty list for an empty
selector, or the selector property directly for a selector of 1 block.  If the selector has multiple blocks, the aggregator will return the sum of the values if all
are numeric; otherwise will return a list containing the property values for each selector block.
This commit also consolidates the "name" and "names" properties, as this commit removes the unnecessary (and confusing) distinction between the two properties.
=> Fixed Implicit Aggregation Support

EasyCommands.Tests/ParameterParsingTests/ParsingTestUtility.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/Operations/SimpleCastTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/Variables/SimpleVariableTests.cs, EasyCommands/Common/Primitives.cs, EasyCommands/Program.cs, docs/EasyCommands/primitives.md, docs/EasyCommands/variables.md
This commit adds a new global variable for "NUMBER_FORMAT" which the user can now set from their script to change the number format used when outputing numbers.
It also changes the default number format used to \#0.\#\#\#\#\#\#\#\#, which ensures that large numbers are not truncated using scientific notation.
This PR fixes #252
=> Added support for custom number formatting

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ParameterParsingTests/BooleanLogicParameterProcessorTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/Variables/ListAggregateConditionTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/Variables/SelectorAggregateConditionTests.cs, EasyCommands/CommandParsers/CommandParameters.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/CommandParsers/ProcessingEngine.cs, EasyCommands/Common/Aggregators.cs, EasyCommands/Common/Types.cs, EasyCommands/Common/Variables.cs
This commit changes aggregation logic so that all/none of an empty list or selector returns true (previously was false).
This commit also removes some characters by refactoring and removing AggregationMode
=> Updated Aggregators to adhere to vacuous truth principles

EasyCommands.Tests/ScriptTests/FunctionalTests/BlockHandlers/RotorBlockTests.cs, EasyCommands/BlockHandlers/RotorBlockHandlers.cs, EasyCommands/Common/Operations.cs, docs/EasyCommands/blockHandlers/rotor.md, docs/EasyCommands/operations.md
This commit implements the ability to reset the rotor limits using a boolean handler.
This commit implements #260.
Pistons have not been implemented but this support doesn't appear to be needed.
=> Added support for turning off rotor limits

EasyCommands.Tests/ScriptTests/FunctionalTests/Variables/SimpleAggregationTests.cs, EasyCommands/Common/Variables.cs
This small MR changes the default behavior of aggregate block properties so that the default values used when no property is specified, "names" is used.  This enables
```set myBatteries to "My Batteries" batteries"```
to provide you the list of battery names, vs the unhelpful sum of battery ratios.
=> Fix Simple Aggregate Property To Use Name if no property is set
