MerlinofMines/EasyCommands

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ScriptTests/MultiThreadingTests.cs, EasyCommands.Tests/ScriptTests/ScriptTest.cs, EasyCommands.Tests/ScriptTests/SimpleCommandExecutionTests.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/CommandParsers/ParameterProcessors.cs, EasyCommands/Commands/CommandParameters.cs, EasyCommands/Commands/Commands.cs, EasyCommands/Common/Types.cs, EasyCommands/Program.cs
Testing out a pull request by submitting the multi-threading changes as a pull request so pandincus can review
=> Multithreading improvements

EasyCommands.Tests/ScriptTests/SimpleCommandExecutionTests.cs, EasyCommands/BlockHandlers/TextSurfaceHandlers.cs, EasyCommands/Program.cs
Also did a small bugfix to TextBlockHandler
=> Fixed issue where empty custom data did not parse correctly

EasyCommands.Tests/ScriptTests/ScriptTest.cs, EasyCommands.Tests/ScriptTests/SimpleCommandExecutionTests.cs, EasyCommands/Program.cs
This commit also exposes a new utility function to set the script to support more use cases in the future where we want to change the script after execution.
This commit fixes #39
=> Fixed bug where updating the script does not restart the program

EasyCommands.Tests/ParameterParsingTests/SimpleVariableParameterProcessorTests.cs, EasyCommands.Tests/ScriptTests/MultiThreadingTests.cs, EasyCommands.Tests/ScriptTests/ScriptTest.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/CommandParsers/ParameterProcessors.cs, EasyCommands/Commands/CommandParameters.cs, EasyCommands/Commands/Commands.cs, EasyCommands/Common/Variables.cs, EasyCommands/Program.cs
This commit adds thread Local Variable Support and default s variable assignment to use thread local variables.
Additionally, this commit adds support for assigning global variables using the "global" keyword.
This commit resolves #51
=> Added Thread Local Variable Support

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ScriptTests/RotorControlTests.cs
This commit adds tests for RotorControl to verify that this script can now run as an EasyCommand script.
It is built on top of #71 which is why that commit is included as well
=> Rotor control migration

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ScriptTests/AirLockManagerTests.cs
This pull request adds a test for AirlockManager as an EasyCommands script
Resolves #21
=> Airlockmanager migration

EasyCommands.Tests/ScriptTests/MultiThreadingTests.cs, EasyCommands/Commands/Commands.cs, EasyCommands/Program.cs
Fixed some of the thread name logic to remove unnecessary prefixes, fix naming for async, and proactively set function call names.
=> Fixed some of the thread name logic

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ParameterParsingTests/ListParameterProcessorTests.cs, EasyCommands.Tests/ParameterParsingTests/OperatorParameterProcessorTests.cs, EasyCommands.Tests/ScriptTests/SimpleListTests.cs, EasyCommands.Tests/TokenParsingTests/BracketParsingTests.cs, EasyCommands.Tests/TokenParsingTests/StringParsingTests.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/CommandParsers/ParameterProcessors.cs, EasyCommands/Commands/CommandParameters.cs, EasyCommands/Commands/Commands.cs, EasyCommands/Common/Operations.cs, EasyCommands/Common/Primitives.cs, EasyCommands/Common/Types.cs, EasyCommands/Common/Variables.cs
Finally, Collection Support is out.
This pull request adds collection support to EasyCommands, enabling the use of Lists of variables.
Functionality includes:
*assign variable to list
*assign list index to value
*retrieval of list values by index
*aggregation of list values, including count, sum, avg, min, max, etc.
*aggregate condition of lists, including all values >, =, < a given value (effectively contains)
*append
*insert
*insert range
*sublist (effectively remove and remove range)
*multi-dimensional list support
=> Collection support enhancement

docs/EasyCommands/examples.md, docs/EasyCommands/index.md
Added Drillbert example and explanation.
Also, added minor updates to the overview page.
=> Added Drillbert example and explanation.

.editorconfig, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/Common/Primitives.cs, EasyCommands/Program.cs, EasyCommands/Properties/AssemblyInfo.cs
This commit permanently fixes the issue with scripts building locally but not being allowed in SpaceEngineers after compiling the script.
=> Fixed issue with prohibited members not failing the build

EasyCommands/CommandParsers/DataProcessors.cs, EasyCommands/CommandParsers/ProcessingEngine.cs
Attempting to fix build by removing the "Immutable" imports
=> Removed bad imports causing build failures

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ParameterParsingTests/SimpleCommandProcessorTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/SimpleWaitCommandTests.cs, EasyCommands.Tests/ScriptTests/ScriptTest.cs, EasyCommands.sln, EasyCommands/CommandParsers/ProcessingEngine.cs, EasyCommands/Commands/Commands.cs, EasyCommands/EasyCommands.csproj, docs/EasyCommands/commands.md, docs/EasyCommands/debugging.md
This commit fixes the Wait command so that it waits the appropriate duration regardless of the run frequency.
Also added an update frequency utility to script tests for changing the update frequency and added missing Wait Command tests
This commit attempts to resolve #120
=> Wait Time Fix

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ScriptTests/FunctionalTests/SimpleCastTests.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/CommandParsers/ProcessingEngine.cs, EasyCommands/Commands/CommandParameters.cs, EasyCommands/Common/Primitives.cs
This PR is a starting point to fix #121.
- 36 tests for the current expected behaviour
- test for the proposed behaviour for `number as bool` 
the 2 variants of the `number as bool` test are mutually exclusive!
One of the casts in the sequence `Vector3 -> Object -> Vector3D` throws the exception 
edit:
- moved the remainig task (behavioral changes) into a seperate issue/PR #139
- added task
=> Fix cast operators

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ScriptTests/BlockHandlerTests/ProjectorBlockTests.cs, EasyCommands/BlockHandlers/ProjectorBlockHandlers.cs, EasyCommands/CommandParsers/ParameterParsers.cs, docs/EasyCommands/blockHandlers/projector.md
This commit adds the ability to get and set the offset and rotation of Projector Blocks, along with some useful properties for getting / setting whether the projector is projecting.
=> Projector Block Improvements

EasyCommands.Tests/ParameterParsingTests/OperatorParameterProcessorTests.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/Common/Operations.cs, EasyCommands/Common/Types.cs, docs/EasyCommands/cheatsheet.md, docs/EasyCommands/operations.md
As suggested in #122 - implements natural log unioperand as "ln"
=> Support nautral log as UniOperand

EasyCommands.Tests/ScriptTests/BlockHandlerTests/JumpDriveBlockTests.cs, EasyCommands/BlockHandlers/JumpDriveBlockHandlers.cs, EasyCommands/CommandParsers/ParameterParsers.cs, docs/EasyCommands/blockHandlers/jumpDrive.md, docs/EasyCommands/cheatsheet.md
This commit adds Jump Drive properties for getting and setting the current jump distance, and for getting the min & max jump distance.  It also adds the Supply property so that you can get or set the Recharge property.
Resolves #111
=> Jump Drive Improvements

EasyCommands.Tests/ScriptTests/FunctionalTests/BlockHandlers/TurretBlockTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/BlockHandlers/WarheadBlockTests.cs, EasyCommands/BlockHandlers/GunBlockHandlers.cs, EasyCommands/BlockHandlers/ShipControllerHandlers.cs, EasyCommands/BlockHandlers/TerminalBlockHandlers.cs, docs/EasyCommands/blockHandlers/gun.md, docs/EasyCommands/blockHandlers/turret.md, docs/EasyCommands/blockHandlers/warhead.md
=> Fixed Turret and Warhead block incorrect default boolean properties

EasyCommands.Tests/ParameterParsingTests/OperatorParameterProcessorTests.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/Common/Operations.cs, EasyCommands/Common/Types.cs, docs/EasyCommands/cheatsheet.md, docs/EasyCommands/operations.md
this PR adds the sign operator, tests and its documentation.
closes #161
=> Add Sign operator

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ParameterParsingTests/SimpleVariableParameterProcessorTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/Operations/TernaryOperatorTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/Variables/VectorVariableTests.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/CommandParsers/ParameterProcessors.cs, EasyCommands/CommandParsers/ProcessingEngine.cs, EasyCommands/Commands/CommandParameters.cs, EasyCommands/Common/Variables.cs, EasyCommands/Program.cs
This is a quick and dirty attempt to implement vectors with variable components, see #159 
There are several issues with this implementation.
* there are priority issues between the operators and the vector declaration
* directly parsing strings had to be disabled to resolve issues between the ternary operator and the vector declaration. As a side effect all test that have quotes around the vector to not work.
* gps parsing in its current form broke
the first point can as far as i can see not be resolved without having delimiters around the vector.
=> Variable Vectors

EasyCommands/CommandParsers/DataProcessors.cs, EasyCommands/CommandParsers/ProcessingEngine.cs, EasyCommands/Commands/Commands.cs, EasyCommands/Commands/Selectors.cs, EasyCommands/Common/Collections.cs, EasyCommands/Common/Items.cs, EasyCommands/Common/Primitives.cs, EasyCommands/Program.cs
This PR contains some character saving chances. 
This resolves mostly around removing `toList` calls. As a side effect this should also remove some double iterations and allocations.
Please take a careful look before accepting.
=> Save Characters

EasyCommands.Tests/ScriptTests/FunctionalTests/BlockHandlers/WheelBlockTests.cs, EasyCommands/BlockHandlers/WheelBlockHandlers.cs, docs/EasyCommands/blockHandlers/suspension.md
Adds attached as a readonly property. (#174)
We should take a look what other properties can be easily incorporated in this PR.
=> Add more Suspension Properties

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ScriptTests/FunctionalTests/Operations/SimplePowerOperatorTests.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/CommandParsers/ParameterProcessors.cs, EasyCommands/CommandParsers/ProcessingEngine.cs, EasyCommands/Commands/CommandParameters.cs, docs/EasyCommands/operations.md
*  Consolidated BiOperand Command Parameters and Processors
*  Added a separate tier for ^ in front of *,/,%
This PR resolves #177
=> Improve Operation Tiers

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ScriptTests/FunctionalTests/BlockHandlers/GunBlockTests.cs, EasyCommands/CommandParsers/ParameterParsers.cs, docs/EasyCommands/blockHandlers/gun.md, docs/EasyCommands/cheatsheet.md
This commit adds the "railgun" keyword along with "fire" and "firing" keywords, which were previously missing.
This commit also adds previously missing tests for Gun Blocks.
=> Gun Improvements

docs/EasyCommands/collections.md, docs/EasyCommands/input.md, docs/EasyCommands/operations.md
This PR resolves #160.
This PR resolves #164
=> Fixed Input and Subtraction Operation docs

EasyCommands.Tests/ScriptTests/ScriptTest.cs, EasyCommands/BlockHandlers/BlockHandlers.cs, EasyCommands/BlockHandlers/CargoBlockHandlers.cs, EasyCommands/BlockHandlers/EngineBlockHandlers.cs, EasyCommands/BlockHandlers/RotorBlockHandlers.cs, EasyCommands/BlockHandlers/TerminalBlockHandlers.cs, EasyCommands/BlockHandlers/TextSurfaceHandlers.cs, EasyCommands/Commands/Selectors.cs, EasyCommands/Program.cs
`BlockHandlerRegistry` needs some changes i guess and i reshuffled `BlockHandlers.cs` a bit.
=> Cache Block and Group retrieval

.github/workflows/dotnet.yml
downgrade image from `windows-latest` to `windows-2019`
=> Update CI Settings

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ScriptTests/ExampleScriptTests/RocketVolleyTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/CacheTests.cs, EasyCommands.Tests/ScriptTests/MockEntityUtility.cs, EasyCommands.Tests/ScriptTests/ScriptTest.cs, EasyCommands/BlockHandlers/BlockHandlers.cs, EasyCommands/BlockHandlers/GunBlockHandlers.cs, EasyCommands/BlockHandlers/HeatVentBlockHandlers.cs, EasyCommands/BlockHandlers/OreDetectorHandlers.cs, EasyCommands/BlockHandlers/ParachuteBlockHandlers.cs, EasyCommands/BlockHandlers/ProjectorBlockHandlers.cs, EasyCommands/BlockHandlers/ShipControllerHandlers.cs, EasyCommands/BlockHandlers/TerminalBlockHandlers.cs, EasyCommands/BlockHandlers/WheelBlockHandlers.cs, EasyCommands/Commands/Selectors.cs, EasyCommands/Common/Cache.cs, EasyCommands/EasyCommands.csproj, EasyCommands/Program.cs
- ~~[ ] move `BlockhandlerRegistry` and caches into a seperate file?~~
=> Memoization 

docs/EasyCommands/collections.md
This PR updates the collection docs to describe how you can add a string to a list.
This PR resolves #221
=> Added docs around how to add strings to lists

EasyCommands.Tests/ScriptTests/FunctionalTests/Operations/SimpleCastTests.cs, EasyCommands.Tests/ScriptTests/ScriptTest.cs, EasyCommands/Program.cs
save some chars and change exception messages
depends on #231
edit: rebased so it merges cleanly
=> Small changes

EasyCommands.Tests/ScriptTests/FunctionalTests/BlockHandlers/BatteryBlockTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/Selectors/SelectorWordTests.cs, EasyCommands/BlockHandlers/BatteryBlockHandlers.cs, EasyCommands/CommandParsers/ParameterParsers.cs, docs/EasyCommands/blockHandlers/battery.md, docs/EasyCommands/blockHandlers/cockpit.md, docs/EasyCommands/cheatsheet.md
Also add helm keyword for cockpits.
=> Added support for getting the input/output limits for batteries.

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ScriptTests/FunctionalTests/BlockHandlers/ThreadBlockTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/MultiThreadingTests.cs, EasyCommands/BlockHandlers/BlockHandlerRegistry.cs, EasyCommands/BlockHandlers/BlockHandlers.cs, EasyCommands/BlockHandlers/GridBlockHandlers.cs, EasyCommands/BlockHandlers/TerminalBlockHandlers.cs, EasyCommands/BlockHandlers/ThreadBlockHandlers.cs, EasyCommands/CommandParsers/CommandParameters.cs, EasyCommands/CommandParsers/ParameterParsers.cs, EasyCommands/CommandParsers/ProcessingEngine.cs, EasyCommands/Commands/Commands.cs, EasyCommands/Common/Types.cs, EasyCommands/Common/Utilities.cs, EasyCommands/EasyCommands.csproj, EasyCommands/Program.cs, docs/EasyCommands/cheatsheet.md, docs/EasyCommands/commands.md, docs/EasyCommands/threads.md
This commit adds better support for managing threads, including a new await command as well as a pseudo block handler to help manage threads.
=> Added Await command and ThreadBlockHandler

EasyCommands.Tests/EasyCommands.Tests.csproj, EasyCommands.Tests/ScriptTests/FunctionalTests/BlockHandlers/TerminalBlockTests.cs, EasyCommands.Tests/ScriptTests/FunctionalTests/Variables/SimpleAggregationTests.cs, EasyCommands/Common/Properties.cs, EasyCommands/EasyCommands.csproj
This commit upgrades EasyCommands dependencies to use the new Automations dependencies.  It also fixes a small bug that prevented reading and writing to properties with reserved keyword names.
Fixes #263
=> Upgraded to Automations version.  Fixed issue with dynamic properties.
